# Generated by Django 5.2.12 on 2026-03-15 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('upc', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('year_published', models.IntegerField(blank=True, null=True)),
                ('min_players', models.IntegerField(blank=True, null=True)),
                ('max_players', models.IntegerField(blank=True, null=True)),
                ('playing_time', models.IntegerField(blank=True, null=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'games',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['bgg_id'], name='games_bgg_id_e8a1a3_idx'), models.Index(fields=['upc'], name='games_upc_b15fa4_idx'), models.Index(fields=['title'], name='games_title_d054a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'party_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_game_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_game_requests', to=settings.AUTH_USER_MODEL)),
                ('party_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_requests', to='catalog.partylist')),
            ],
            options={
                'db_table': 'game_requests',
            },
        ),
        migrations.CreateModel(
            name='PartyListGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.game')),
                ('party_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_list_games', to='catalog.partylist')),
            ],
            options={
                'db_table': 'party_list_games',
            },
        ),
        migrations.CreateModel(
            name='PartyListShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], default='view', max_length=20)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='catalog.partylist')),
                ('shared_with_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_party_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'party_list_shares',
            },
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('bgg_sync', 'BGG Sync'), ('manual', 'Manual'), ('barcode', 'Barcode Scan')], default='manual', max_length=50)),
                ('is_lent', models.BooleanField(default=False)),
                ('lent_to', models.CharField(blank=True, max_length=255)),
                ('lent_date', models.DateField(blank=True, null=True)),
                ('lent_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_collections', to='catalog.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_collections',
            },
        ),
        migrations.CreateModel(
            name='LendingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lent_to', models.CharField(max_length=255)),
                ('lent_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('lent_notes', models.TextField(blank=True)),
                ('return_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lending_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lending_history',
                'indexes': [models.Index(fields=['user'], name='lending_his_user_id_86b7ba_idx'), models.Index(fields=['game'], name='lending_his_game_id_45a649_idx'), models.Index(fields=['returned_date'], name='lending_his_returne_47da3f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='partylist',
            index=models.Index(fields=['owner'], name='party_lists_owner_i_20096f_idx'),
        ),
        migrations.AddIndex(
            model_name='gamerequest',
            index=models.Index(fields=['party_list'], name='game_reques_party_l_1a8d88_idx'),
        ),
        migrations.AddIndex(
            model_name='gamerequest',
            index=models.Index(fields=['owner'], name='game_reques_owner_i_ba42a0_idx'),
        ),
        migrations.AddIndex(
            model_name='partylistgame',
            index=models.Index(fields=['party_list'], name='party_list__party_l_8592c9_idx'),
        ),
        migrations.AddIndex(
            model_name='partylistgame',
            index=models.Index(fields=['game'], name='party_list__game_id_678df6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partylistgame',
            unique_together={('party_list', 'game')},
        ),
        migrations.AddIndex(
            model_name='partylistshare',
            index=models.Index(fields=['party_list'], name='party_list__party_l_bdbdfa_idx'),
        ),
        migrations.AddIndex(
            model_name='partylistshare',
            index=models.Index(fields=['shared_with_user'], name='party_list__shared__da68dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partylistshare',
            unique_together={('party_list', 'shared_with_user')},
        ),
        migrations.AddIndex(
            model_name='usercollection',
            index=models.Index(fields=['user'], name='user_collec_user_id_e52aac_idx'),
        ),
        migrations.AddIndex(
            model_name='usercollection',
            index=models.Index(fields=['game'], name='user_collec_game_id_a7e1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='usercollection',
            index=models.Index(fields=['is_lent'], name='user_collec_is_lent_861ac3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercollection',
            unique_together={('user', 'game')},
        ),
    ]
