#!/usr/bin/env bash
# =============================================================================
# Board Game Catalog — One-time server setup for boardgames.tendimensions.com
# =============================================================================
#
# Run this script ONCE on the Linode after the tendimensions-web container
# has been moved off port 80.  It creates nginx virtual host configs that
# route traffic by hostname to the correct Docker container.
#
# SSL is handled entirely by Cloudflare.  This server only speaks HTTP on
# port 80.  Do NOT run certbot here.
#
# Usage:
#   On the server:
#     sudo bash ~/boardgames/server-setup.sh
#
#   From your Windows machine:
#     scp web/server-setup.sh user@ssh.tendimensions.com:~/boardgames/
#     ssh user@ssh.tendimensions.com "sudo bash ~/boardgames/server-setup.sh"
#
# Prerequisites:
#   - nginx installed  (sudo apt install nginx)
#   - Docker + docker compose installed
#   - tendimensions-web container moved to 127.0.0.1:8080  (see below)
#   - boardgame_catalog container running on 127.0.0.1:8000
#
# Before running this script, update ~/Website/docker-compose.yml:
#   Change:  - "80:80"
#   To:      - "127.0.0.1:8080:80"
#   Then:    cd ~/Website && docker compose up -d
#
# =============================================================================

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────

BOARDGAMES_DOMAIN="boardgames.tendimensions.com"
MAIN_DOMAIN="tendimensions.com"
BOARDGAMES_PORT="8000"
MAIN_PORT="8080"

# ── Colour helpers ────────────────────────────────────────────────────────────

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
step()  { echo -e "\n${CYAN}▶  $*${NC}"; }
ok()    { echo -e "   ${GREEN}✓  $*${NC}"; }
warn()  { echo -e "   ${YELLOW}⚠  $*${NC}"; }
fail()  { echo -e "   ${RED}✗  $*${NC}"; }

# ── Root check ────────────────────────────────────────────────────────────────

if [[ $EUID -ne 0 ]]; then
  fail "This script must be run as root (use: sudo bash $0)"
  exit 1
fi

# ── nginx present? ────────────────────────────────────────────────────────────

step "Checking for nginx..."
if ! command -v nginx &>/dev/null; then
  fail "nginx is not installed."
  echo "     Install it with:  sudo apt update && sudo apt install -y nginx"
  exit 1
fi
ok "nginx found: $(nginx -v 2>&1 | head -1)"

# ── Port 80 free? (must be free for host nginx to bind) ──────────────────────

step "Checking port 80..."
if ss -tlnp 2>/dev/null | grep -q ":80 "; then
  fail "Something is already listening on port 80."
  echo ""
  echo "     Port 80 must be free before host nginx can start."
  echo "     If tendimensions-web is still bound to 0.0.0.0:80, fix it first:"
  echo ""
  echo "       1. Edit ~/Website/docker-compose.yml"
  echo "            Change:  - \"80:80\""
  echo "            To:      - \"127.0.0.1:8080:80\""
  echo "       2. cd ~/Website && docker compose up -d"
  echo ""
  exit 1
fi
ok "Port 80 is free"

# ── Check containers are running ─────────────────────────────────────────────

step "Checking Docker containers..."

if docker ps --format '{{.Names}}' | grep -q "^boardgame_catalog$"; then
  ok "boardgame_catalog is running on port ${BOARDGAMES_PORT}"
else
  warn "boardgame_catalog container is not running."
  warn "Deploy the app first:  .\\deploy.ps1 -Ssh user@ssh.tendimensions.com"
fi

if docker ps --format '{{.Names}}' | grep -q "^tendimensions-web$"; then
  ok "tendimensions-web is running"
else
  warn "tendimensions-web container is not running."
fi

# ── Write nginx config: boardgames.tendimensions.com ─────────────────────────

step "Writing nginx config for ${BOARDGAMES_DOMAIN}..."

NGINX_BOARDGAMES="/etc/nginx/sites-available/${BOARDGAMES_DOMAIN}"

cat > "${NGINX_BOARDGAMES}" << NGINX_EOF
# Board Game Catalog — ${BOARDGAMES_DOMAIN}
# Generated by server-setup.sh
# SSL is handled by Cloudflare — no HTTPS config needed here.

server {
    listen 80;
    listen [::]:80;
    server_name ${BOARDGAMES_DOMAIN};

    location / {
        proxy_pass         http://127.0.0.1:${BOARDGAMES_PORT};
        proxy_http_version 1.1;

        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;

        # Hardcoded https because Cloudflare always delivers HTTPS to end users.
        # Django reads this header to treat requests as secure without redirecting.
        proxy_set_header   X-Forwarded-Proto https;

        # Timeouts — BGG sync can take up to 60 s for large collections
        proxy_read_timeout    90s;
        proxy_connect_timeout 10s;
        proxy_send_timeout    90s;

        client_max_body_size 10M;
    }
}
NGINX_EOF

ok "Config written to ${NGINX_BOARDGAMES}"

# ── Write nginx config: tendimensions.com ────────────────────────────────────

step "Writing nginx config for ${MAIN_DOMAIN}..."

NGINX_MAIN="/etc/nginx/sites-available/${MAIN_DOMAIN}"

cat > "${NGINX_MAIN}" << NGINX_EOF
# Main website — ${MAIN_DOMAIN}
# Generated by server-setup.sh
# Proxies to the tendimensions-web Docker container on port ${MAIN_PORT}.
# Internal routing (e.g. umami analytics) is handled by that container's nginx.
# SSL is handled by Cloudflare.

server {
    listen 80;
    listen [::]:80;
    server_name ${MAIN_DOMAIN} www.${MAIN_DOMAIN};

    location / {
        proxy_pass         http://127.0.0.1:${MAIN_PORT};
        proxy_http_version 1.1;

        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
    }
}
NGINX_EOF

ok "Config written to ${NGINX_MAIN}"

# ── Enable both sites ─────────────────────────────────────────────────────────

step "Enabling sites..."

for DOMAIN in "${BOARDGAMES_DOMAIN}" "${MAIN_DOMAIN}"; do
  LINK="/etc/nginx/sites-enabled/${DOMAIN}"
  if [[ -L "${LINK}" ]]; then
    warn "Symlink already exists for ${DOMAIN}. Skipping."
  else
    ln -s "/etc/nginx/sites-available/${DOMAIN}" "${LINK}"
    ok "Enabled: ${DOMAIN}"
  fi
done

# ── Disable default site (it conflicts as a catch-all) ───────────────────────

if [[ -L /etc/nginx/sites-enabled/default ]]; then
  rm /etc/nginx/sites-enabled/default
  ok "Removed default catch-all site"
fi

# ── Test and start nginx ──────────────────────────────────────────────────────

step "Testing nginx configuration..."
if nginx -t 2>&1; then
  ok "nginx config valid"
else
  fail "nginx config has errors — see output above."
  exit 1
fi

step "Starting nginx..."
systemctl enable nginx
systemctl start nginx
ok "nginx started and enabled on boot"

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  nginx is routing traffic:${NC}"
echo ""
echo    "    https://${BOARDGAMES_DOMAIN}  →  localhost:${BOARDGAMES_PORT} (boardgame_catalog)"
echo    "    https://${MAIN_DOMAIN}         →  localhost:${MAIN_PORT} (tendimensions-web)"
echo ""
echo    "  Useful diagnostics:"
echo    "     sudo nginx -t                          # validate config"
echo    "     sudo systemctl status nginx            # nginx health"
echo    "     docker logs boardgame_catalog          # app logs"
echo    "     docker logs tendimensions-web          # main site logs"
echo -e "${GREEN}  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
